apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patch-delete-nginx-deployment.yaml
  - path: patch-delete-nginx-service.yaml
  - path: patch-db-aws.yaml
  - path: patch-be-aws.yaml
  - path: patch-fe-aws.yaml
  - path: patch-migrate-job.yaml

